### PR TITLE
require kigkonsult/icalcreator with composer instead of internal inclusion

### PR DESCRIPTION
**Pull request by manuelbrossard**
Hello,

To upgrade with PHP7, it is needed to use the last version of icalcreator.
Thank you.

### CODE REVIEW

**Comment by BorisMorel** [comment]
Ok. And about BC ? Any infos ?

**Comment by lenybernard** [comment]
@BorisMorel, These changes are ok, no BC for me.

**Comment by MrBanjo** [comment]
Hello,
I'm using this bundle for a project but sadly php 7 throws me some depreciations. I'm really interested by this merge request. Do you think you can accept this PR any time soon?

Thanks.

**Comment by BorisMorel** [comment]
Thanks !

**Pull request merged**
