### PR TITLE
Stable version of kigkonsult/icalcreator

### PR DESCRIPTION
**Pull request by LeJeanbono**
Version dev-master = v2.22.5

### CODE REVIEW

**Comment by BorisMorel** [comment]
Hi,

Can you update the README too. Part on composer default stability is deprecated.

Regards.

**Comment by LeJeanbono** [comment]
Okay

**Comment by LeJeanbono** [comment]
Is it right ?

**Comment by BorisMorel** [comment]
Thanks. But i can't merge your composer.json.

**Comment by LeJeanbono** [comment]
Ignore commit https://github.com/BorisMorel/IcalBundle/pull/19/commits/5d467ba9e0d785573573e666baaa617b200a9576
I did it for my personnal use.

**Pull request closed without merging**
